const SpectrumCards: [string, string][] = [
  ["Schlechter Schauspieler", "Guter Schauspieler"],
  ["Basic", "Hipster"],
  ["Wertlos", "Unbezahlbar"],
  ["Nature", "Nurture"],
  ["Passiert schleichend", "Passiert plötzlich"],
  ["Job", "Karriere"],
  ["Rund", "Spitz"],
  ["Beweis, dass Gott existiert", "Beweis, dass Gott nicht existiert"],
  ["Geliebt", "Gehasst"],
  ["Die helle Seite der Macht", "Die dunkle Seite der Macht"],
  ["Dumm", "Brilliant"],
  ["Kunsthandwerk", "Massenware"],
  ["Niemand macht es", "Alle machen es"],
  ["Short lived", "Long lived"],
  ["Gefährlicher Job", "Sicherer Job"],
  ["Fantasy", "Science-Fiction"],
  ["Schlicht", "Extravagant"],
  ["Schlechter Ruf", "Guter Ruf"],
  ["Unmodisch", "Modisch"],
  ["Freiheitskämpfer", "Terrorist"],
  ["Schlechte Superkraft", "Gute Superkraft"],
  ["Ineffektiv", "Effektiv"],
  ["Besser wenn heiß", "Besser wenn kalt"],
  ["Quadratisch", "Rund"],
  ["Temporär", "Permanent"],
  ["Sieht aus wie eine Person", "Sieht nicht aus wie eine Person"],
  ["Uncool", "Cool"],
  ["Schlimmste lebende Person", "Großartigste lebende Person"],
  ["Unterbewertet", "Überbewertet"],
  ["Unordentliches Essen", "Vornehmes Essen"],
  ["Unverzeilich", "Verzeilich"],
  ["Fehlschlag", "Meisterstück"],
  ["Harmlos", "Schädlich"],
  ["Gryffindor", "Slytherin"],
  ["Unhygienisch", "Hygienisch"],
  ["Schlechte Musik", "Gute Musik"],
  ["Nutzlos", "Nützlich"],
  ["Film, den Gozilla besser machen würde", "Film, den Gozilla schlechter machen würde"],
  ["Unwichtig", "Wichtig"],
  ["Easy to spell", "Hard to spell"],
  ["Laster", "Tugend"],
  ["Unterbewerteter Musiker", "Überbewerteter Musiker"],
  ["Unbeliebte Aktivität", "Beliebte Aktivität"],
  ["Aufgeteilt", "Ganz"],
  ["Unzuverlässig", "Zuverlässig"],
  ["Einfach zu töten", "Schwierig zu töten"],
  ["Instabil", "Stabil"],
  ["Rundes Tier", "Spitzes Tier"],
  ["Schlechte Fernsehsendung", "Gute Fernsehsendung"],
  ["Traditionell männlich", "Traditionell weiblich"],
  ["Unnützer Körperteil", "Nützlicher Körperteil"],
  ["Mode-Erscheinung", "Klassiker"],
  ["Schwach", "Stark"],
  ["Eklig im Müsli", "Lecker im Müsli"],
  ["Schlecht", "Gut"],
  ["Geringe Suchtgefahr", "Hohe Suchtgefahr"],
  ["Nutzlos bei einem Notfall", "Hilfreich bei einem Notfall"],
  ["Für Kinder", "Für Erwachsene"],
  ["Bösewicht", "Held"],
  //["Underrated thing to do", "Overrated thing to do"],
  ["Langweilig", "Aufregend"],
  ["Guter Gestank", "Ekliger Gestank"],
  ["Unbeliebt", "beliebt"],
  ["Freund", "Feind"],
  ["Nutzlose Erfindung", "Nützliche Erfindung"],
  ["Liberal", "Konservativ"],
  ["Heiß", "Kalt"],
  ["Normal", "Komisch"],
  ["Farblos", "Bunt"],
  ["Kalorienarm", "Kalorienbombe"],
  ["Einfaches Thema", "Schwieriges Thema"],
  ["Unbekannt", "Berühmt"],
  ["Selten", "Häufig"],
  ["Unsexy Emoji", "Sexy Emoji"],
  ["Billig", "Teuer"],
  //["Underrated weapon", "Overrated weapon"],
  ["Fühlt sich schlecht an", "Fühlt sich gut an"],
  //["Inessential", "Essential"],
  ["Dreckig", "Sauber"],
  ["Benötigt Glück", "Benötigt Können"],
  ["Geschmacklos", "Geschmackvoll"],
  ["Langweiliges Thema", "Spannednes Thema"],
  ["Lässig", "Formell"],
  ["Unterbezahlt", "Überbezahlt"],
  ["Trocken", "Nass"],
  ["Unterbewertete Fähigkeit", "Überbewertete Fähigkeit"],
  ["Verboten", "Empfohlen"],
  ["Trauriges Lied", "Fröhliches Lied"],
  ["Zerbrechlich", "Unverwüstlich"],
  ["Genie", "Idiot"],
  ["Gut", "Böse"],
  ["Schlimmster Tag des Jahres", "Bester Tag des Jahres"],
  ["Schlechte Angewohnheit", "Gute Angewohnheit"],
  ["Katzen-Liebhaber", "Hunde-Liebhaber"],
  ["Weise", "Intelligent"],
  ["Schwierige Tätigkeit", "Leichte Tätigkeit"],
  ["Mentale Anstrengung", "Körperliche Anstrengung"],
  ["Eindeutiges Thema", "Kontroverses Thema"],
  ["Untalentiert", "Talentiert"],
  //["Hard to find", "Easy to find"],
  //["Ugly Man", "Beautiful Man"],
  //["Hard to remember", "Easy to remember"],
  //["Lowbrow, anspruchslose Kunst", "Highbrow"],
  ["Ungesund", "Gesund"],
  //["Bad man", "Good man"],
  ["Historisch wichtig", "Historisch unwichtig"],
  ["Unbehaart", "Behaart"],
  ["Fest", "Biegsam"],
  ["Normales Haustier", "Exotisches Haustier"],
  ["Introvertiert", "Extrovertiert"],
  ["Das Buch war besser", "Die Verfilmung war besser"],
  ["Schlechter Film", "Guter Film"],
  ["Hässlisch", "Gutaussehend"],
  ["Erwachsen", "Kindisch"],
  //["Underrated thing to own", "Overrated thing to own"],
  ["Gewöhnlich", "Außergewöhnlich"],
  ["Schwierige Aussprache", "Einfache Aussprache"],
  //["Poorly made", "Well made"],
  ["Kein Sandwich", "Ein Sandwich"],
  ["Gefährlich", "Sicher"],
  ["Von kultureller Bedeutung", "Ohne kulturelle Bedeutung"],
  ["Freiwillig", "Verpflichtend"],
  ["Unterbewerteter Buchstabe des Alphabets", "Überbewerteter Buchstabe des Alphabets"],
  //["Low quality", "High quality"],
  //["Unsexy Tier", "Sexy Tier"],
  ["Stiller Ort", "Lauter Ort"],
  ["Comedy", "Drama"],
  ["Brauche ich", "Will ich haben"],
  ["Trockenes Essen", "Nasses Essen"],
  ["Ersetzbar", "Unersetzbar"],
  ["Schlechter Sportler aller Zeiten", "Bester Sportler aller Zeiten"],
  ["Unethisch", "Ethisch"],
  ["Langweiliges Hobby", "Spannendes Hobby"],
  ["Schlecht als Pizzabelag", "Gut als Pizzabelag"],
  ["Dystopie", "Utopie"],
  ["Rau", "Glatt"],
  //["Bad for you", "Good for you"],
  ["Friedlich", "Kriegsähnlich"],
  ["Unterbewerteter Film", "Überbewerteter Film"],
  ["Schmeckt nicht", "Schmeckt gut"],
  ["Sport", "Spiel"],
  ["Trauriger Film", "Fröhlicher Film"],
  ["Zeitverschwendung", "Gut genutzte Zeit"],
  //["Least evil company", "Most evil company"],
  ["Snack", "Mahlzeit"],
  ["Unglaublich", "Glaubhaft"],
  //["Trashy", "Klassiker"],
  ["Stinkt", "Riecht gut"],
  ["Star Wars", "Star Trek"],
  ["Unheimliches Tier", "Niedliches Tier"],
  //["Mainstream", "Niche"],
  ["Dunkel", "Hell"],
  ["Unterberwerteter Schauspieler", "Überbewerteter Schauspieler"],
  ["Schwierig zu benutzen", "Einfach zu benutzen"],
  //["Tired", "Wired"],
  ["80er", "90er"],
  ["Schlechter Mensch", "Guter Mensch"],
  ["Nahrungsmittel", "Haute cuisine"],
  ["Weich", "Hart"],
  //["Normal thing to own", "Weird thing to own"],
  ["Glatt", "Wellig"],
  ["Gutes Vorbild", "Schlechtes Vorbild"],
  ["Unnützer Studiengang", "Nützlicher Studiengang"],
  ["Gemeine Person", "Nette Person"],
  ["Action-Film", "Abenteurfilm"],
];

const AdvancedSpectrumCards: [string, string][] = [
  ["Kurz", "Lang"],
  ["Schlimmstes Jahr aller Zeiten", "Bestes Jahr aller Zeiten"],
  ["Berühmt", "Berüchtigt"],
  //["Least powerful god", "Most powerful god"],
  ["Unsexy Farbe", "Sexy Farbe"],
  ["Zu deinem Vorteil", "Für das Gemeinwohl"],
  ["Schlechter Präsident", "Guter Präsident"],
  ["Merkwürdig", "Komisch"],
  ["Abwandlung", "Original"],
  ["Etikette", "Mannieren"],
  ["Das Schlimmste", "Das Beste"],
  ["Kleine Zahl", "Große Zahl"],
  ["Nicht genug", "Zu viel"],


  ["Hard to sit on", "Easy to sit on"],
  ["Talent", "Skill"],
  ["Worst era to time travel", "Best era to time travel"],
  ["Not huggable", "Huggable"],
  ["Heterogeneous", "Homogeneous"],
  ["Out of control", "In control"],
  ["Popular", "Elitist"],
  ["Non-partisan", "Partisan"],
  ["Dog name", "Cat name"],
  ["Little known fact", "Well known fact"],
  ["Socialist", "Capitalist"],
  ["Bad candy", "Good candy"],
  ["Traditional", "Radical"],
  ["Bad mouthfeel", "Good mouthfeel"],
  ["Illegal", "Legal"],
  ["Never on time", "Always on time"],
  ["Won't live to 100", "Will live to 100"],
  ["Bad Disney character", "Good Disney character"],
  ["Similar", "Identical"],
  ["Limp", "Firm"],
  ["Funny topic", "Serious topic"],
  ["Unscented", "Scented"],
  ["Horizontal", "Vertical"],
  ["Small", "Tiny"],
  ["Ugly word", "Beautiful word"],
  ["Tick", "Tock"],
  ["Bad advice", "Good advice"],
  ["Illegal", "Prohibited"],
  ["Not art", "Art"],
  ["Gossip", "News"],
  ["Guilty pleasure", "Actually just bad"],
  ["Old fashioned", "Avant garde"],
  ["True", "False"],
  ["Normal greeting", "Weird greeting"],
  ["Dictatorship", "Democracy"],
  ["Powerless", "Powerful"],
  ["Vapes", "Doesn't Vape"],
  ["Boring person", "Fun person"],
  ["Underrated book", "Overrated book"],
  ["Deep thought", "Shallow thought"],
  ["Bad school", "Good school"],
  ["Conventional wisdom", "Fringe belief"],
  ["Worst chore", "Best chore"],
  ["Endangered species", "Overpopulated species"],
  ["Blue", "Green"],
  ["Fruit", "Vegetable"],
  ["Science", "Pseudoscience"],
  ["Small talk", "Heavy topic"],
  ["Bad investment", "Good investment"],
  ["Stationary", "Mobile"],
  ["Local issue", "Global issue"],
  ["Thrilling", "Terrifying"],
  ["Nerd", "Jock"],
  ["Expected", "Unexpected"],
  ["Person you could beat up", "Person who'd beat you up"],
  ["Limited", "Infinite"],
  ["Casual event", "Formal event"],
  ["Unreasonable phobia", "Reasonable phobia"],
  ["Underrated game", "Overrated game"],
  ["Religious", "Sacrilegious"],
  ["Mild", "Spicy"],
  ["Genuine person", "Phony person"],
  ["Unnatural", "Natural"],
  ["Secret", "Public Knowledge"],
  ["Too small", "Too big"],
  ["Art", "Commerce"],
  ["One hit wonder", "Pop icon"],
  ["Unsexy Pokémon", "Sexy Pokémon"],
  ["Quiet", "Loud"],
  ["Inclusive", "Exclusive"],
  ["Bad dog (breed)", "Good dog (breed)"],
];

export const AllCards = [...SpectrumCards, ...AdvancedSpectrumCards];
