const SpectrumCards: [string, string][] = [
  ["Schlechter Schauspieler", "Guter Schauspieler"],
  ["Basic", "Hipster"],
  ["Wertlos", "Unbezahlbar"],
  ["Nature", "Nurture"],
  ["Passiert schleichend", "Passiert plötzlich"],
  ["Job", "Karriere"],
  ["Rund", "Spitz"],
  ["Beweis, dass Gott existiert", "Beweis, dass Gott nicht existiert"],
  ["Geliebt", "Gehasst"],
  ["Die helle Seite der Macht", "Die dunkle Seite der Macht"],
  ["Dumm", "Brilliant"],
  ["Kunsthandwerk", "Massenware"],
  ["Niemand macht es", "Alle machen es"],
  ["Short lived", "Long lived"],
  ["Gefährlicher Job", "Sicherer Job"],
  ["Fantasy", "Science-Fiction"],
  ["Schlicht", "Extravagant"],
  ["Schlechter Ruf", "Guter Ruf"],
  ["Unmodisch", "Modisch"],
  ["Freiheitskämpfer", "Terrorist"],
  ["Schlechte Superkraft", "Gute Superkraft"],
  ["Ineffektiv", "Effektiv"],
  ["Besser wenn heiß", "Besser wenn kalt"],
  ["Quadratisch", "Rund"],
  ["Temporär", "Permanent"],
  ["Sieht aus wie eine Person", "Sieht nicht aus wie eine Person"],
  ["Uncool", "Cool"],
  ["Schlimmste lebende Person", "Großartigste lebende Person"],
  ["Unterbewertet", "Überbewertet"],
  ["Unordentliches Essen", "Vornehmes Essen"],
  ["Unverzeilich", "Verzeilich"],
  ["Fehlschlag", "Meisterstück"],
  ["Harmlos", "Schädlich"],
  ["Gryffindor", "Slytherin"],
  ["Unhygienisch", "Hygienisch"],
  ["Schlechte Musik", "Gute Musik"],
  ["Nutzlos", "Nützlich"],
  ["Film, den Gozilla besser machen würde", "Film, den Gozilla schlechter machen würde"],
  ["Unwichtig", "Wichtig"],
  ["Easy to spell", "Hard to spell"],
  ["Laster", "Tugend"],
  ["Unterbewerteter Musiker", "Überbewerteter Musiker"],
  ["Unbeliebte Aktivität", "Beliebte Aktivität"],
  ["Aufgeteilt", "Ganz"],
  ["Unzuverlässig", "Zuverlässig"],
  ["Einfach zu töten", "Schwierig zu töten"],
  ["Instabil", "Stabil"],
  ["Rundes Tier", "Spitzes Tier"],
  ["Schlechte Fernsehsendung", "Gute Fernsehsendung"],
  ["Traditionell männlich", "Traditionell weiblich"],
  ["Unnützer Körperteil", "Nützlicher Körperteil"],
  ["Mode-Erscheinung", "Klassiker"],
  ["Schwach", "Stark"],
  ["Eklig im Müsli", "Lecker im Müsli"],
  ["Schlecht", "Gut"],
  ["Geringe Suchtgefahr", "Hohe Suchtgefahr"],
  ["Nutzlos bei einem Notfall", "Hilfreich bei einem Notfall"],
  ["Für Kinder", "Für Erwachsene"],
  ["Bösewicht", "Held"],
  //["Underrated thing to do", "Overrated thing to do"],
  ["Langweilig", "Aufregend"],
  ["Guter Gestank", "Ekliger Gestank"],
  ["Unbeliebt", "beliebt"],
  ["Freund", "Feind"],
  ["Nutzlose Erfindung", "Nützliche Erfindung"],
  ["Liberal", "Konservativ"],
  ["Heiß", "Kalt"],
  ["Normal", "Komisch"],
  ["Farblos", "Bunt"],
  ["Kalorienarm", "Kalorienbombe"],
  ["Einfaches Thema", "Schwieriges Thema"],
  ["Unbekannt", "Berühmt"],
  ["Selten", "Häufig"],
  ["Unsexy Emoji", "Sexy Emoji"],
  ["Billig", "Teuer"],
  //["Underrated weapon", "Overrated weapon"],
  ["Fühlt sich schlecht an", "Fühlt sich gut an"],
  //["Inessential", "Essential"],
  ["Dreckig", "Sauber"],
  ["Benötigt Glück", "Benötigt Können"],
  ["Geschmacklos", "Geschmackvoll"],
  ["Langweiliges Thema", "Spannednes Thema"],
  ["Lässig", "Formell"],
  ["Unterbezahlt", "Überbezahlt"],
  ["Trocken", "Nass"],
  ["Unterbewertete Fähigkeit", "Überbewertete Fähigkeit"],
  ["Verboten", "Empfohlen"],
  ["Trauriges Lied", "Fröhliches Lied"],
  ["Zerbrechlich", "Unverwüstlich"],
  ["Genie", "Idiot"],
  ["Gut", "Böse"],
  ["Schlimmster Tag des Jahres", "Bester Tag des Jahres"],
  ["Schlechte Angewohnheit", "Gute Angewohnheit"],
  ["Katzen-Liebhaber", "Hunde-Liebhaber"],
  ["Weise", "Intelligent"],
  ["Schwierige Tätigkeit", "Leichte Tätigkeit"],
  ["Mentale Anstrengung", "Körperliche Anstrengung"],
  ["Eindeutiges Thema", "Kontroverses Thema"],
  ["Untalentiert", "Talentiert"],
  //["Hard to find", "Easy to find"],
  //["Ugly Man", "Beautiful Man"],
  //["Hard to remember", "Easy to remember"],
  //["Lowbrow, anspruchslose Kunst", "Highbrow"],
  ["Ungesund", "Gesund"],
  //["Bad man", "Good man"],
  ["Historisch wichtig", "Historisch unwichtig"],
  ["Unbehaart", "Behaart"],
  ["Fest", "Biegsam"],
  ["Normales Haustier", "Exotisches Haustier"],
  ["Introvertiert", "Extrovertiert"],
  ["Das Buch war besser", "Die Verfilmung war besser"],
  ["Schlechter Film", "Guter Film"],
  ["Hässlisch", "Gutaussehend"],
  ["Erwachsen", "Kindisch"],
  //["Underrated thing to own", "Overrated thing to own"],
  ["Gewöhnlich", "Außergewöhnlich"],
  ["Schwierige Aussprache", "Einfache Aussprache"],
  //["Poorly made", "Well made"],
  ["Kein Sandwich", "Ein Sandwich"],
  ["Gefährlich", "Sicher"],
  ["Von kultureller Bedeutung", "Ohne kulturelle Bedeutung"],
  ["Freiwillig", "Verpflichtend"],
  ["Unterbewerteter Buchstabe des Alphabets", "Überbewerteter Buchstabe des Alphabets"],
  //["Low quality", "High quality"],
  //["Unsexy Tier", "Sexy Tier"],
  ["Stiller Ort", "Lauter Ort"],
  ["Comedy", "Drama"],
  ["Brauche ich", "Will ich haben"],
  ["Trockenes Essen", "Nasses Essen"],
  ["Ersetzbar", "Unersetzbar"],
  ["Schlechter Sportler aller Zeiten", "Bester Sportler aller Zeiten"],
  ["Unethisch", "Ethisch"],
  ["Langweiliges Hobby", "Spannendes Hobby"],
  ["Schlecht als Pizzabelag", "Gut als Pizzabelag"],
  ["Dystopie", "Utopie"],
  ["Rau", "Glatt"],
  //["Bad for you", "Good for you"],
  ["Friedlich", "Kriegsähnlich"],
  ["Unterbewerteter Film", "Überbewerteter Film"],
  ["Schmeckt nicht", "Schmeckt gut"],
  ["Sport", "Spiel"],
  ["Trauriger Film", "Fröhlicher Film"],
  ["Zeitverschwendung", "Gut genutzte Zeit"],
  //["Least evil company", "Most evil company"],
  ["Snack", "Mahlzeit"],
  ["Unglaublich", "Glaubhaft"],
  //["Trashy", "Klassiker"],
  ["Stinkt", "Riecht gut"],
  ["Star Wars", "Star Trek"],
  ["Unheimliches Tier", "Niedliches Tier"],
  //["Mainstream", "Niche"],
  ["Dunkel", "Hell"],
  ["Unterberwerteter Schauspieler", "Überbewerteter Schauspieler"],
  ["Schwierig zu benutzen", "Einfach zu benutzen"],
  //["Tired", "Wired"],
  ["80er", "90er"],
  ["Schlechter Mensch", "Guter Mensch"],
  ["Nahrungsmittel", "Haute cuisine"],
  ["Weich", "Hart"],
  //["Normal thing to own", "Weird thing to own"],
  ["Glatt", "Wellig"],
  ["Gutes Vorbild", "Schlechtes Vorbild"],
  ["Unnützer Studiengang", "Nützlicher Studiengang"],
  ["Gemeine Person", "Nette Person"],
  ["Action-Film", "Abenteurfilm"],
];

const AdvancedSpectrumCards: [string, string][] = [
  ["Kurz", "Lang"],
  ["Schlimmstes Jahr aller Zeiten", "Bestes Jahr aller Zeiten"],
  ["Berühmt", "Berüchtigt"],
  //["Least powerful god", "Most powerful god"],
  ["Unsexy Farbe", "Sexy Farbe"],
  ["Zu deinem Vorteil", "Für das Gemeinwohl"],
  ["Schlechter Präsident", "Guter Präsident"],
  ["Merkwürdig", "Komisch"],
  ["Abwandlung", "Original"],
  ["Etikette", "Mannieren"],
  ["Das Schlimmste", "Das Beste"],
  ["Kleine Zahl", "Große Zahl"],
  ["Nicht genug", "Zu viel"],
  ["Gemütlich", "Ungemütlich"],
  ["Talent", "Übung"],
  ["Schlechteste Era als Ziel einer Zeitreise", "Beste Era als Ziel einer Zeitreise"],
  //["Not huggable", "Huggable"],
  ["Heterogen", "Homogen"],
  ["Ausser Kontroller", "Unter Kontrolle"],
  ["Proletenhaft", "Elitär"],
  ["Unparteiisch", "Parteiisch"],
  ["Hundename", "Katzenname"],
  //["Little known fact", "Well known fact"],
  ["Sozialistisch", "Kapitalistisch"],
  //["Bad candy", "Good candy"],
  ["Traditionell", "Radikal"],
  //["Bad mouthfeel", "Good mouthfeel"],
  ["Illegal", "Legal"],
  ["Unpünktlich", "Pünktlich"],
  ["Wird keine 100 Jahre alt", "Wird über 100 Jahre alt"],
  ["Schlechte Disney Figur", "Gute Disney Figur"],
  ["Ähnlich", "Identisch"],
  ["Schlaff", "Steif"],
  ["Witziges Thema", "Ernstes Thema"],
  ["Geruchlos", "Duftend"],
  ["Horizontal", "Vertikal"],
  ["Klein", "Winzig"],
  ["Hässliches Wort", "Schönes Wort"],
  //["Tick", "Tock"],
  ["Schlechter Rat", "Guter Rat"],
  ["Illegal", "Verboten"],
  ["Nicht Kunst", "Kunst"],
  ["Klatsch", "Nachrichten"],
  //["Guilty pleasure", "Actually just bad"],
  ["Altmodisch", "Neumodisch"],
  ["Wahr", "Falsch"],
  ["Normale Begrüßung", "Komische Begrüßung"],
  ["Diktatur", "Demokratie"],
  ["Machtlos", "Mächtig"],
  //["Dampft", "Dampft Nicht"],
  ["Langweiler", "Adrenalinjunkie"],
  ["Unterbewertetes Buch", "Überbewertetes Buch"],
  //["Deep thought", "Shallow thought"],
  ["Schlechte Schule", "Gute Schule"],
  //["Conventional wisdom", "Fringe belief"],
  ["Schlimmste Arbeit im Haushalt", "Beste Arbeit im Haushalt"],
  ["Bedrohte Spezies", "Überbevölkerte Spezies"],
  ["Blau", "Grün"],
  ["Obst", "Gemüse"],
  ["Wisenschaft", "Pseudo-Wissenschaft"],
  ["Small talk", "Bedeutungsvolles Gespräch"],
  ["Schlechtes Investment", "Gutes Investment"],
  ["Stationär", "Mobil"],
  ["Lokales Problem", "Weltweites Problem"],
  ["Aufregend", "Furchterregend"],
  ["Nerd", "Muskelprotz"],
  ["Vorhersehbar", "Unvorhersehbar"],
  //["Person you could beat up", "Person who'd beat you up"],
  ["Begrenzt", "Unbegrenzt"],
  //["Casual event", "Formal event"],
  ["Unbegründete Phobie", "Begründete Phobie"],
  ["Unterbewertetes Spiel", "Überbewertetes Spiel"],
  ["Religiös", "Frevelhaft"],
  ["Mild", "Scharf"],
  //["Genuine person", "Phony person"],
  ["Unnatürlich", "Natürlich"],
  ["Geheim", "Öffentlich Bekannt"],
  ["Zu klein", "Zu groß"],
  ["Kunst", "Kommerz"],
  ["One-Hit-Wunder", "Pop-Ikone"],
  ["Unsexy Pokémon", "Sexy Pokémon"],
  ["Leise", "Laut"],
  //["Inclusive", "Exclusive"],
  ["Schlechte Hunderasse", "Gute Hunderasse"],
];

export const AllCards = [...SpectrumCards, ...AdvancedSpectrumCards];
